### ISSUE TITLE
dart:html gives: Uncaught EvalError

### ISSUE THREAD

**Issue by jimmyff** [dart-gde/chrome.dart#264]
When I try to use `dart:html` I get the following error:
```
Uncaught EvalError: Refused to evaluate a string as JavaScript because 'unsafe-eval' is not an allowed source of script in the following Content Security Policy directive: "script-src 'self' blob: filesystem: chrome-extension-resource:".
```

**Comment by jimmyff** [comment]
I also get this when trying the `demo` application code

**Comment by adambender** [comment]
Hey jimmyff, that error usually appears if you haven't set the CSP flag to true in your pubspec.yaml. Are you using your own pubspec.yaml or the one from the demo?

**Comment by tonyclickspace** [comment]
Here's a sample pubspec.yaml file that enables the CSP flag, should clear up your issue:

```
name: YourApp
description: Your Description
dependencies:
  chrome: any
transformers:
- chrome
- $dart2js:
    csp: true
```
